### ISSUE TITLE
Let's make this official?

### ISSUE THREAD

**Issue by ndelangen** [vwxyutarooo/types-storybook-vue#1]
@vwxyutarooo What do you need to make this the official way? Where should we add these types? 

Should we add them here like has been done for react:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/85ffb53c7faa2a50cc4cd680c8dd8e601c50e376/types/storybook__react

**Comment by vwxyutarooo** [comment]
@ndelangen 
> Should we add them here like has been done for react:

Yeah I think so. I'd like to make it to the official. Because it seems bit more have to do such as making test code, I didn't it yet. Anyway I will create PR to it in thins weekend :)
Thanks!

**Comment by ndelangen** [comment]
👏

**Comment by vwxyutarooo** [comment]
[Somebody](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23048) sent PR before [I did](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23190) 😂.
It is now official anyway 🎉
